sudo: required
services:
  -docker

before_install:
  -docker build -t abhinavsrivastav667/docker-react -f Dockerfile.dev .

script:
  -docker run abhinavsrivastav667/docker-react npm run test -- --coverage
