sudo: required
services:
  - docker

before_install:
  - docker build -t abhinavsrivastav667/docker-react -f Dockerfile.dev .

script:
  - docker run abhinavsrivastav667/docker-react npm run test -- --coverage

#DockerReact-env.27ewmjbyup.ap-south-1.elasticbeanstalk.com
deploy:
   provider: elasticbeanstalk
   region: "ap-south-1"
   app: "docker-react"
   env: "DockerReact-env"
   bucket_name: "elasticbeanstalk-ap-south-1-214177960663"
   bucket_path: "docker-react"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"
